### PR TITLE
refactor: onboard.ubq.fi

### PR DESCRIPTION
**Pull request by molecula451**

### CODE REVIEW

**Comment by molecula451** [comment]
This does it, but!

on live [pay.ubq.fi](https://pay.ubq.fi/onboarding) i get:
Screenshot from 2024-03-01 16-23-59

**which in localhost replicates  itself**

looks like relates to: https://github.com/ubiquity/pay.ubq.fi/pull/154#issuecomment-1950229969

and indeed **it's not** related to this refactor

@ubiquity/software-development rfc

**Comment by gentlementlegen** [comment]
@molecula451 Seems to be introduced by changes from https://github.com/ubiquity/pay.ubq.fi/commit/3c59ca011f3232a0f33fa54037aadc6cdb91e1c9

`defaultConfig` used to have a default value, and now defaults to `{}`, so of course `keys` is undefined. Sensible fix would be to set some default values so `keys` exist, or merging an object containing `keys` into the default config.

**Comment by molecula451** [comment]
> `defaultConfig` used to have a default value, and now defaults to `{}`, so of course `keys` is undefined. Sensible fix would be to set some default values so `keys` exist, or merging an object containing `keys` into the default config.

but as per your comment you are into it? https://github.com/ubiquity/pay.ubq.fi/pull/154#issuecomment-1950229969 no? so to clarify it's not part of the refactor ([moving repos](https://github.com/ubiquity/pay.ubq.fi/issues/171)) to avoid clutter 😄

**Comment by gentlementlegen** [comment]
@molecula451 This was already created, you can import the package from https://www.npmjs.com/package/@ubiquibot/configuration

**Comment by molecula451** [comment]
> @molecula451 This was already created, you can import the package from https://www.npmjs.com/package/@ubiquibot/configuration

so we deprecate the submodule import? https://github.com/ubiquity/ubiquibot/tree/cb084909ab332f67bba271b5a17b907d21716bd1

**Comment by molecula451** [comment]
leaving it to be part of https://github.com/ubiquity/onboard.ubq.fi/issues/4, it looses scope of https://github.com/ubiquity/pay.ubq.fi/issues/171, need further debugging cc @rndquu

**Comment by gentlementlegen** [comment]
@molecula451 all right will take care of it then, otherwise I am fine with this PR, except the commit messages

**Review by gentlementlegen — APPROVED** [review]

**Comment by molecula451** [comment]
> @molecula451 all right will take care of it then, otherwise I am fine with this PR, except the commit messages

you mean `refactor: onboard.ubq.fi #1`? , suggest welcome

**Comment by gentlementlegen** [comment]
image
It's preferable to have messages representing the changes done by that commit

**Comment by molecula451** [comment]
>  It's preferable to have messages representing the changes done by that commit

the messages reflect that, if i put "update" on that message it's because i'm updating something, check the committed code for instance, tho everyone workflow it's different, it's good your suggestion tho

**Comment by molecula451** [comment]
mergin because @FernandVEYRIER it's taking care of #4 at "development" which basically it's putting the app to work, which is already live bugged at `pay.ubq.fi/onboarding`

**Pull request merged**
